In [53]:
import numpy as np
from sklearn.decomposition import TruncatedSVD
from sklearn.metrics.pairwise import cosine_similarity
from numpy.linalg import norm

# Define two matrices with different shapes
matrix1 = np.array([[1, 2], [3, 4], [5, 6]])
matrix2 = np.array([[1, 2, 3], [4, 5, 6]])

# Apply SVD to obtain a lower-dimensional representation of the matrices
n_components = 2  # number of components to keep
svd = TruncatedSVD(n_components=n_components)
matrix1_transformed = svd.fit_transform(matrix1)
matrix2_transformed = svd.fit_transform(matrix2)

# Compute cosine similarity between the transformed matrices
similarity_matrix = cosine_similarity(matrix1_transformed, matrix2_transformed)


In [13]:
similarity_matrix

array([[0.99991642, 0.97165678],
       [0.98610042, 0.99827168],
       [0.97629697, 0.99997139]])

In [14]:
matrix1.shape

(3, 2)

In [15]:
matrix2.shape

(2, 3)

In [16]:
similarity_matrix.shape

(3, 2)

In [19]:
import numpy as np
from sklearn.decomposition import TruncatedSVD
from sklearn.metrics.pairwise import cosine_similarity

# Define two matrices with different shapes
matrix1 = np.array([[1, 2], [3, 4], [5, 6]])
matrix2 = np.array([[1, 2, 3], [4, 5, 6]])

# Apply SVD to obtain a lower-dimensional representation of the matrices
n_components = 2  # number of components to keep
svd = TruncatedSVD(n_components=n_components)
matrix1_transformed = svd.fit_transform(matrix1)
matrix2_transformed = svd.fit_transform(matrix2)

# Compute cosine similarity between the transformed matrices
similarity_matrix = cosine_similarity(matrix1_transformed, matrix2_transformed)

# Iterate over the similarity matrix and retrieve corresponding elements from matrix1 and matrix2
for i in range(similarity_matrix.shape[0]):
    for j in range(similarity_matrix.shape[1]):
        # Retrieve the indices of the corresponding elements in matrix1 and matrix2
        matrix1_index = i
        matrix2_index = j

        # Retrieve the corresponding elements from matrix1 and matrix2
        matrix1_element = matrix1[matrix1_index]
        matrix2_element = matrix2[matrix2_index]

        # Print the corresponding elements and their similarity score
        similarity_score = similarity_matrix[i, j]
        print(f"Matrix1 element {matrix1_element} and Matrix2 element {matrix2_element} have a similarity score of {similarity_score}.")

Matrix1 element [1 2] and Matrix2 element [1 2 3] have a similarity score of 0.9999164221029999.
Matrix1 element [1 2] and Matrix2 element [4 5 6] have a similarity score of 0.9716567842088734.
Matrix1 element [3 4] and Matrix2 element [1 2 3] have a similarity score of 0.98610041936458.
Matrix1 element [3 4] and Matrix2 element [4 5 6] have a similarity score of 0.9982716843917039.
Matrix1 element [5 6] and Matrix2 element [1 2 3] have a similarity score of 0.9762969710849807.
Matrix1 element [5 6] and Matrix2 element [4 5 6] have a similarity score of 0.9999713898673188.


In [28]:
import numpy as np
from sklearn.decomposition import TruncatedSVD
from sklearn.metrics.pairwise import cosine_similarity

# Define two matrices with different shapes
matrix1 = np.array([[1, 2], [3, 4], [5, 6]])
matrix2 = np.array([[1, 2, 3], [4, 5, 6]])

# Apply SVD to obtain a lower-dimensional representation of the matrices
n_components = 2  # number of components to keep
svd = TruncatedSVD(n_components=n_components)
matrix1_transformed = svd.fit_transform(matrix1)
matrix2_transformed = svd.fit_transform(matrix2)

# Compute cosine similarity between the transformed matrices
similarity_matrix = cosine_similarity(matrix1_transformed, matrix2_transformed)

# Iterate over the similarity matrix and retrieve corresponding elements from matrix1 and matrix2
for i, row in enumerate(similarity_matrix):
    for j, score in enumerate(row):
        # Retrieve the corresponding elements from matrix1 and matrix2
        matrix1_element = matrix1[i]
        matrix2_element = matrix2[j]

        # Print the corresponding elements and their similarity score
        print(f"Matrix1 element {matrix1_element} and Matrix2 element {matrix2_element} have a similarity score of {score}.")


Matrix1 element [1 2] and Matrix2 element [1 2 3] have a similarity score of 0.9999164221029997.
Matrix1 element [1 2] and Matrix2 element [4 5 6] have a similarity score of 0.9716567842088734.
Matrix1 element [3 4] and Matrix2 element [1 2 3] have a similarity score of 0.9861004193645797.
Matrix1 element [3 4] and Matrix2 element [4 5 6] have a similarity score of 0.9982716843917037.
Matrix1 element [5 6] and Matrix2 element [1 2 3] have a similarity score of 0.9762969710849806.
Matrix1 element [5 6] and Matrix2 element [4 5 6] have a similarity score of 0.9999713898673188.


In [24]:
valid_pairs

[]

In [27]:
matrix1[0]

array([1, 2])

In [26]:
len(matrix1[0])

2

In [25]:
len(matrix2[0])

3

In [29]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

# define two matrices with different shapes
matrix1 = np.array([[1, 2], [3, 4], [5, 6]])
matrix2 = np.array([[1, 2, 3], [4, 5, 6]])

# initialize an empty list to store the similarity scores
similarity_scores = []

# compute the similarity between each pair of columns
for i in range(matrix1.shape[1]):
    for j in range(matrix2.shape[1]):
        # select the i-th column from matrix1 and the j-th column from matrix2
        column1 = matrix1[:, i]
        column2 = matrix2[:, j]

        # reshape the columns to have a compatible shape for cosine_similarity
        column1 = column1.reshape(1, -1)
        column2 = column2.reshape(1, -1)

        # compute the cosine similarity between the two columns
        score = cosine_similarity(column1, column2)[0][0]

        # add the similarity score to the list
        similarity_scores.append((i, j, score))

# print the similarity scores
for score in similarity_scores:
    print(f"Similarity between column {score[0]} of matrix1 and column {score[1]} of matrix2: {score[2]}")


ValueError: Incompatible dimension for X and Y matrices: X.shape[1] == 3 while Y.shape[1] == 2

In [30]:
import numpy as np
from sklearn.decomposition import TruncatedSVD
from sklearn.metrics.pairwise import cosine_similarity

# Define two matrices with different number of columns
matrix1 = np.array([[1, 2], [3, 4], [5, 6]])
matrix2 = np.array([[1, 2, 3], [4, 5, 6]])

# Apply SVD to reduce the dimensionality of the matrices to a common number of dimensions
n_components = 2
svd = TruncatedSVD(n_components=n_components)
matrix1_reduced = svd.fit_transform(matrix1)
matrix2_reduced = svd.fit_transform(matrix2)

# Compute cosine similarity between the pairs of elements in the original matrices
similarity_scores = np.zeros((matrix1.shape[0], matrix2.shape[0])) # initialize similarity scores matrix
for i in range(matrix1.shape[0]):
    for j in range(matrix2.shape[0]):
        similarity_scores[i,j] = cosine_similarity([matrix1_reduced[i]], [matrix2_reduced[j]])

# Print the similarity scores pair by pair in the original matrices
for i in range(matrix1.shape[0]):
    for j in range(matrix2.shape[0]):
        print(f"Similarity score between element {matrix1[i]} in matrix1 and element {matrix2[j]} in matrix2 is {similarity_scores[i,j]}")


Similarity score between element [1 2] in matrix1 and element [1 2 3] in matrix2 is 0.9999164221029999
Similarity score between element [1 2] in matrix1 and element [4 5 6] in matrix2 is 0.9716567842088734
Similarity score between element [3 4] in matrix1 and element [1 2 3] in matrix2 is 0.98610041936458
Similarity score between element [3 4] in matrix1 and element [4 5 6] in matrix2 is 0.9982716843917039
Similarity score between element [5 6] in matrix1 and element [1 2 3] in matrix2 is 0.9762969710849806
Similarity score between element [5 6] in matrix1 and element [4 5 6] in matrix2 is 0.9999713898673187


In [32]:
import numpy as np
from sklearn.decomposition import TruncatedSVD
from sklearn.metrics.pairwise import cosine_similarity

# Define two matrices with different number of columns
matrix1 = np.array([[1, 2], [3, 4], [5, 6]])
matrix2 = np.array([[1, 2, 3], [4, 5, 6]])

# Apply SVD to reduce the dimensionality of the matrices to a common number of dimensions
n_components = 2
svd = TruncatedSVD(n_components=n_components)
matrix1_reduced = svd.fit_transform(matrix1)
matrix2_reduced = svd.fit_transform(matrix2)

# Compute cosine similarity between the two specified elements
similarity_score = cosine_similarity([matrix1_reduced[0]], [matrix2_reduced[0]])

# Print the similarity score between the two specified elements
print(f"Similarity score between element {matrix1[0][0]} in matrix1 and element {matrix2[0][0]} in matrix2 is {similarity_score}")


Similarity score between element 1 in matrix1 and element 1 in matrix2 is [[0.99991642]]


In [33]:
import numpy as np
from sklearn.decomposition import TruncatedSVD
from sklearn.metrics.pairwise import cosine_similarity

# Define two matrices with different number of columns
matrix1 = np.array([[1, 2], [3, 4], [5, 6]])
matrix2 = np.array([[1, 2, 3], [4, 5, 6]])

# Apply SVD to reduce the dimensionality of the matrices to a common number of dimensions
n_components = 2
svd = TruncatedSVD(n_components=n_components)
matrix1_reduced = svd.fit_transform(matrix1)
matrix2_reduced = svd.fit_transform(matrix2)

# Compute cosine similarity between all pairs of elements
similarity_matrix = cosine_similarity(matrix1_reduced, matrix2_reduced)

# Print the similarity scores for all pairs of elements
for i in range(matrix1.shape[0]):
    for j in range(matrix2.shape[0]):
        similarity_score = similarity_matrix[i][j]
        print(f"Similarity score between element {matrix1[i][0]} in matrix1 and element {matrix2[j][0]} in matrix2 is {similarity_score}")


Similarity score between element 1 in matrix1 and element 1 in matrix2 is 0.9999164221029998
Similarity score between element 1 in matrix1 and element 4 in matrix2 is 0.9716567842088734
Similarity score between element 3 in matrix1 and element 1 in matrix2 is 0.98610041936458
Similarity score between element 3 in matrix1 and element 4 in matrix2 is 0.9982716843917039
Similarity score between element 5 in matrix1 and element 1 in matrix2 is 0.9762969710849806
Similarity score between element 5 in matrix1 and element 4 in matrix2 is 0.9999713898673187


In [34]:
import numpy as np
from sklearn.decomposition import TruncatedSVD
from sklearn.metrics.pairwise import cosine_similarity

# Define two matrices with different number of columns
matrix1 = np.array([[1, 2], [3, 4], [5, 6]])
matrix2 = np.array([[1, 2, 3], [4, 5, 6]])

# Apply SVD to reduce the dimensionality of the matrices to a common number of dimensions
n_components = 2
svd = TruncatedSVD(n_components=n_components)
matrix1_reduced = svd.fit_transform(matrix1)
matrix2_reduced = svd.fit_transform(matrix2)

# Compute cosine similarity between all pairs of elements
similarity_matrix = cosine_similarity(matrix1_reduced, matrix2_reduced)

# Print the similarity scores for all pairs of elements
for i in range(matrix1.shape[0]):
    for j in range(matrix2.shape[0]):
        similarity_score = similarity_matrix[i][j]
        print(f"Similarity score between element {matrix1[i]} in matrix1 and element {matrix2[j]} in matrix2 is {similarity_score}")


Similarity score between element [1 2] in matrix1 and element [1 2 3] in matrix2 is 0.9999164221029998
Similarity score between element [1 2] in matrix1 and element [4 5 6] in matrix2 is 0.9716567842088734
Similarity score between element [3 4] in matrix1 and element [1 2 3] in matrix2 is 0.98610041936458
Similarity score between element [3 4] in matrix1 and element [4 5 6] in matrix2 is 0.9982716843917039
Similarity score between element [5 6] in matrix1 and element [1 2 3] in matrix2 is 0.9762969710849806
Similarity score between element [5 6] in matrix1 and element [4 5 6] in matrix2 is 0.9999713898673187


In [35]:
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

matrix1 = np.array([[1, 2], [3, 4], [5, 6]])
matrix2 = np.array([[1, 2, 3], [4, 5, 6]])

# initialize similarity matrix with zeros
similarity_matrix = np.zeros((matrix1.shape[0], matrix2.shape[1]))

for i in range(matrix1.shape[0]):
    for j in range(matrix2.shape[1]):
        # compute cosine similarity between ith row of matrix1 and jth column of matrix2
        similarity_matrix[i][j] = cosine_similarity([matrix1[i]], [matrix2[:,j]])[0,0]

print(similarity_matrix)

[[0.97618706 0.99654576 1.        ]
 [0.92163538 0.96561576 0.98386991]
 [0.90055164 0.95103407 0.97341717]]
The history saving thread hit an unexpected error (OperationalError('database or disk is full')).History will not be written to the database.


In [38]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

matrix1 = np.array([[1, 2], [3, 4], [5, 6]])
matrix2 = np.array([[1, 2, 3], [4, 5, 6]])

similarity_matrix = np.zeros((matrix1.shape[0] * matrix1.shape[1], matrix2.shape[0] * matrix2.shape[1]))

for i in range(matrix1.shape[0]):
    for j in range(matrix1.shape[1]):
        # Get the (i, j)-th element of matrix1 and reshape it to a column vector
        vector1 = matrix1[i, j].reshape(-1, 1)
        for k in range(matrix2.shape[0]):
            for l in range(matrix2.shape[1]):
                # Get the (k, l)-th element of matrix2 and reshape it to a row vector
                vector2 = matrix2[k, l].reshape(1, -1)
                # Compute the cosine similarity between vector1 and vector2
                similarity_matrix[i * matrix1.shape[1] + j, k * matrix2.shape[1] + l] = cosine_similarity(vector1, vector2)

# Print the similarity matrix
print(similarity_matrix)


[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [41]:
vector1 = matrix1[0, 0].reshape(-1, 1)
vector1

array([[1]])

In [44]:
vector2 = matrix2[0, 1].reshape(1, -1)
vector2

array([[2]])

In [47]:
cosine_similarity([[1]], [[2]])

array([[1.]])

In [49]:
from sklearn.metrics.pairwise import cosine_similarity

a = [1]
b = [5]
cos_sim = cosine_similarity([a], [b])
print(cos_sim[0][0])  # Output: 0.9999999999999998

1.0


In [51]:
a = 1
b = 5

cosine_similarity = a * b / (abs(a) * abs(b))
print(cosine_similarity)

1.0


In [54]:
cosine = np.dot(a,b)/(norm(a)*norm(b))
cosine

1.0